#' Simulated cross-lagged dataset
#'
#' A simulated cross-lagged dataset with 2 measures (x and y) assessed
#' three times each (x1-x3, y1-y3). The cross-lagged model was generated by
#' \code{get_crosslagged_model()} and was fed to [simsem::generate()] with population
#' parameter values:
#' * x(t) ~ .7\*x(t-1)
#' * y(t) ~ .7\*x(t-1)
#' * x(t) ~ .4\*y(t-1)
#' * y(t) ~ .4\*y(t-1)
#' * x(t) ~~ .35\*x(t)
#' * y(t) ~~ .35\*y(t)
#' * y(t) ~~ .25\*x(t)
#'
#'
#' @format A data frame with 500 rows and 6 variables:
#' \describe{
#'   \item{x1}{Numeric variable}
#'   \item{x2}{Numeric variable}
#'   \item{x3}{Numeric variable}
#'   \item{y1}{Numeric variable}
#'   \item{y2}{Numeric variable}
#'   \item{y3}{Numeric variable}
#' }
#' @source Simulated data using the \code{simsem} package
"df"
