# make table to copy-paste in excel
#' Generate publication table from lavaan models
#'
#' @description
#' This function generates a publication table from a list of lavaan models
#' to be exported or copy-pasted (e.g. into Excel). The table shows all
#' parameters with operator "~" (i.e. regression paths) with significance level:
#' \itemize{
#' \item{\code{***}}{p < .001}
#' \item{\code{**}}{p < .01}
#' \item{\code{*}}{p < .05}
#' \item{\code{+}}{p < .10}
#' }
#'
#' Each column is a different outcome variable/lavaan model, each row is
#' a different predictor.
#'
#' @param ana List of lavaan models
#' @param check_same_format (logical) Whether to force all models to have the same predictors
#'
#' @return data.frame with predictors and coefficients (and significance level) in each model
#' @export
#'
#' @examples
#' library(lavaan)
#' ana <- list()
#' ana$y1 <- sem("y1 ~ x1+x2", df)
#' ana$y2 <- sem("y2 ~ x1+x2", df)
#' ana |> make_pub_table_from_lavaan_models()
#'
#' @concept publications
make_pub_table_from_lavaan_models <- function(ana, check_same_format=TRUE)
{
  "
  input: ana list (list of lavaan models)
  out: df with IVs and estimate+pvalue for each target
  "

  pe <- lapply(ana, parameterEstimates)
  pe <- lapply(pe, function(x) x[x$op=="~",])

  # check  that all summaries have the same format
  if(check_same_format)
  {
    same_row_orders <- lapply(pe, function(x) all(x[,"rhs"] == pe[[1]][,"rhs"]))
    if (!all(unlist(same_row_orders))) stop("Not all summaries have the same format")
  }

  # get estimates, p-value from each model
  out <- subset(pe[[1]], select=rhs) |> rename(Predictor=rhs)
  for(s in pe)
  {
    # postproc p-value
    s$sig <- weights::starmaker(s$pvalue, symbols=c("***", "**", "*", "+"))

    # concat est (2 decimals) and sig
    s$est_sig <- paste0(sprintf('%.2f',s$est), s$sig)

    # store in table
    v_out <- c("est", "pvalue", "sig", "est_sig")[4]
    out[,ncol(out)+1:length(v_out)] <- s[,v_out]


  }

  # colnames
  if(length(v_out)==1 & !is.null(names(ana))) names(out)[2:ncol(out)] <- names(ana)

  #out
  return(out)
}


# make table to copy-paste in excel from broom::tidy() output
#' Generate publication table from broom::tidy summaries
#'
#' @description
#' This function generates a publication table from a list of tidy summaries
#' to be exported or copy-pasted (e.g. into Excel). The table shows all
#' coefficients in the 'term' column with significance level:
#' \itemize{
#' \item{\code{***}}{p < .001}
#' \item{\code{**}}{p < .01}
#' \item{\code{*}}{p < .05}
#' \item{\code{+}}{p < .10}
#' }
#'
#' Each column is a different outcome variable/tidy summary, each row is
#' a different predictor.
#'
#' @param ana List of tidy summaries
#'
#' @return data.frame with predictors and coefficients (and significance level) in each model
#' @export
#'
#' @examples
#' library(broom)
#' ana <- list()
#' ana$y1 <- lm(y1 ~ x1+x2, df) |> tidy()
#' ana$y2 <- lm(y2 ~ x1+x2, df) |> tidy()
#' ana |> make_pub_table_from_broom_tidy()
#'
#' @concept publications
make_pub_table_from_broom_tidy <- function(ana)
{
  "
  input: ana list (list of tidy outputs)
  out: df with IVs and estimate+pvalue for each target
  "
  # make dfs
  ana <- ana |> lapply(as.data.frame)

  # get estimates, p-value from each model
  out <- ana[[1]][c("term")]
  for(i in 1:length(ana))
  {
    # ith analysis
    a <- ana[[i]]
    y <- names(ana)[i]

    # postproc p-value
    a$sig <- weights::starmaker(a$p.value, symbols=c("***", "**", "*", "+"))

    # concat est (2 decimals) and sig
    a[,y] <- paste0(sprintf('%.2f',a$estimate), a$sig)

    # store in table
    a <- a[,c("term", y)]
    out <- out |> full_join(a, by="term")

  }

  # rename as Predictor
  out <- out |> rename(Predictor=term)

  #out
  return(out)
}



# get list of significant/trend effects from a pub table
#' Extract significant effects from a publication table
#'
#' This function extracts the significant effects from a publication table generated by any
#' of the \code{make_pub_table_from_...()} functions.
#'
#' @param table Publication generated for lavaan models or tidy summaries
#' @param pattern Regular expression used to find significant effects (default is any * or +)
#' @param fixed (logical) Whether pattern is to be searched as is (TRUE)
#' or as a regular expression (FALSE)
#'
#' @return data.frame with columns Outcome, Predictor, and Sign
#' (indicating whether the coefficient is positive or negative)
#' @export
#'
#' @examples
#' library(lavaan)
#' ana <- list()
#' ana$y1 <- sem("y1 ~ x1+x2", df)
#' ana$y2 <- sem("y2 ~ x1+x2", df)
#' pub <- ana |> make_pub_table_from_lavaan_models()
#' pub |> get_sig_effects_from_pub_table()
#'
#' @concept publications
get_sig_effects_from_pub_table <- function(table, pattern="\\*|\\+", fixed=F)
{
  # get significant predictors with outcome
  sig <- table |>
    remove_rownames() |>
    column_to_rownames("Predictor") |>
    apply(1:2, grepl, pattern=pattern, fixed=fixed) |>
    which(arr.ind=T) |>
    (\(m)(data.frame(Predictor=rownames(m), m, row.names=NULL)))() |>
    select(-row) |>
    mutate(col=names(table |> select(-1))[col]) |>
    rename(Outcome=col) |>
    select(Outcome, Predictor)

  # add sign
  sig$Sign <- NA
  for(i in 1:nrow(sig)) sig$Sign[i] <- table |>
    filter(Predictor == sig$Predictor[i]) |>
    select(all_of(sig$Outcome[i])) |>
    substr(1,1)
  sig$Sign <- (sig$Sign == "-") |> ifelse("-", "+")

  # out
  return(sig)
}


# compare sig effects from two pub tables
#' Compare significant effects from two publication tables
#'
#' This function prints to console which effects are significant in table1 but not in table2,
#' and which are significant in table2 but not in table1. The two tables are
#' publication tables generated by any of the \code{make_pub_table_from_...()} functions
#'
#' @param table1 A publication table
#' @param table2 Another publication table
#' @param pattern Pattern used to determine significant effects (default is *)
#' @param fixed (logical) Whether pattern is to be searched as is (TRUE)
#' or as a regular expression (FALSE)
#'
#' @export
#'
#' @examples
#' library(lavaan)
#' ana <- list()
#' ana$y1 <- sem("y1 ~ x1+x2", df, missing="ml.x")
#' ana$y2 <- sem("y2 ~ x1+x2", df, missing="ml.x")
#' pub_sem <- ana |> make_pub_table_from_lavaan_models()
#'
#'library(broom)
#' ana <- list()
#' ana$y1 <- lm(y1 ~ x1+x2, df) |> tidy()
#' ana$y2 <- lm(y2 ~ x1+x2, df) |> tidy()
#' pub_lm <- ana |> make_pub_table_from_broom_tidy()
#'
#' # sensitivity analysis: effect of missing data
#' pub_lm |> compare_sig_effects_in_two_pub_tables(pub_sem)
#'
#' @concept publications
compare_sig_effects_in_two_pub_tables <- function(table1, table2, pattern="*", fixed=T)
{
  # get significant effects in both tables
  sig <- list(table1, table2) |>
    lapply(\(t) t |>
             get_sig_effects_from_pub_table(pattern=pattern, fixed=fixed) |>
             with(paste0(Outcome, ": ", Predictor, " (", Sign, ")")))

  # output
  cat("_______________________________\n")
  cat(pattern |> paste("in table1 but not in table2:\n"))
  (!sig[[1]] %in% sig[[2]]) |> (\(v)sig[[1]][v])() |> print()

  cat("_______________________________\n")
  cat(pattern |> paste("in table2 but not in table1:\n"))
  (!sig[[2]] %in% sig[[1]]) |> (\(v)sig[[2]][v])() |> print()
}
